controllers/AreasComunsController.php
<?
namespace app\controllers;

use app\components\maskComponent;
use Yii;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\AreasComunsModel;

class AreasComunsController extends Controller{

    public function actionListaArea(){
        if(Yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        $query = (new \yii\db\Query())
        ->select(
            "area.id,
            cond.nomeCondominio,
            area.nome,
            area.metragem,
            area.taxa,
            area.lotacaoMax,
            area.dataCadastro,
            area.from_condominio")
        ->from('t_areacomum area')
        ->innerJoin('t_condominio cond', 'cond.id = area.from_condominio');

        $paginacao= new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $areas = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('lista-area', [
            'areas' => $areas,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastroArea(){
        return $this->render('cadastro-area');
    }

    public function actionRealizaCadastroArea(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new AreasComunsModel();
            foreach($request->post() as $field=>$value){
                if($field == 'taxa'){
                    $getMani[$field] = maskComponent::money($value);
                }else{
                    $getMani[$field] = $value;
                }
            }
            $model->attributes = $getMani;
            $model->save();
            return $this->redirect(['areas-comuns/lista-area']);
            }
        return $this->render('cadastro-area');
    }

    public static function listaAreaSelect(){
        $query = AreasComunsModel::find();

        return $query->orderBy('nome')->all();
    }

    public static function listaAreaSelectFrom($from){
        $query = AreasComunsModel::find();
        $data = $query->where(['from_areacomum' => $from])->orderBy('nome')->all();
        return $data;
    }

    public function actionListaAreaApi(){
        $request = \yii::$app->request;
        $query = AreasComunsModel::find();
        $data = $query->where(['from_areacomum' => $request->post()])->orderBy('nome')->all();

        $dados = array();
        $i = 0;

        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nome'] = $d['nome'];
            $i++;
        }
        return json_encode($dados);
    }

    public function actionEditaArea(){
        $this->layout = false;
        $request = \yii::$app->request;
        if ($request->isGet) {
            $query = AreasComunsModel::find();
            $areas = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-area',[
            'edit' => $areas
        ]);
    }

    public function actionRealizaEdicao(){
        $request = \yii::$app->request;
        
        if ($request->isPost) {

            $model = AreasComunsModel::findOne($request->post('id'));
            $model->attributes = $request->post();
        
            if ($model->update()) {
                return $this->redirect(['areas-comuns/lista-area',
                    'myAlert' => [
                        'type' => 'success',
                        'msg' => 'Registro editado com sucesso!'
                    ]
                ]);
            } else {
                return $this->redirect(['areas-comuns/lista-area',
                    'myAlert' => [
                        'type' => 'warning',
                        'msg' => 'Nenhum registro foi editado.'
                    ]
                ]);
            }
        }
    }

    public function actionDeletaArea(){
        $request = \yii::$app->request;

        if ($request->isGet) {
            $model = AreasComunsModel::findOne($request->get('id'));
            if ($model->delete()) {
                return $this->redirect(['areas-comuns/lista-area',
                    'myAlert' => [
                        'type' => 'success',
                        'msg' => 'Registro deletado com sucesso!'
                    ]
                ]);
            } else {
                return $this->redirect(['areas-comuns/lista-area',
                'myAlert' => [
                    'type' => 'danger',
                    'msg' => 'Não foi possível deletar o registro.'
                    ]
                ]);
            }
        }
    }
}
?>

views/areas-comuns/cadastro-area.php
<?

use app\controllers\CondominiosController;
use yii\helpers\Url;

$this->title = 'Cadastrar | Área Comum';

$url_site = Url::base($schema = true);
?>

<h3 class="text-center mt-5" >Cadastrar Área Comum</h3>
<form id="cadastroArea" action="<?= Url::to(['areas-comuns/realiza-cadastro-area'])?>" class="my-5" method="post">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="areaCondo">A qual condomínio esta área pertence?</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="from_condominio"  required>
                <option value="" disabled selected>Selecione o Condomínio</option>
                <? foreach(CondominiosController::listaCondominioSelect() as $dado){?>
                        <option value="<?=$dado['id']?>"><?=$dado['nomeCondominio']?></option>
                <?}?>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="nome">Nome da Área</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="nome" required placeholder="Ex.: Salão de Festas">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="metragem">Metragem (m²)</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="metragem" required>
        </div>
        <div class="form-group col-md-4">
            <label for="taxa">Taxa de Reserva (opcional)</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="taxa" id="maskMoney">
        </div>
        <div class="form-group col-md-4">
            <label for="lotacaoMax">Lotação Máxima</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="lotacaoMax" required>
        </div>
    </div>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">
    
    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-info mr-2 buttonEnviar">Cadastrar</button>
            <a class="btn btn-sm btn-outline-secondary" href="?r=areas-comuns/lista-area" role="button">Ir para a listagem</a>
        </div>
    </div>
</form>

views/areas-comuns/edita-area.php
<?

use app\components\maskComponent;
use app\components\selectedComponent;
use yii\helpers\Url;
use app\controllers\CondominiosController;

$url_site = Url::base(true);
?>

<h3 class="text-center mt-5" >Editar Área Comum</h3>
<form id="cadastroArea" action="<?= Url::to(['areas-comuns/realiza-edicao'])?>" class="my-5" method="post">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="areaCondo">A qual condomínio esta área pertence?</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="from_condominio"  required>
                <option value="" disabled selected>Selecione o Condomínio</option>
                <? foreach(CondominiosController::listaCondominioSelect() as $dado){?>
                        <option value="<?=$dado['id']?>"<?=selectedComponent::isSelected($dado['id'], $edit['from_condominio'])?>><?=$dado['nomeCondominio']?></option>
                <?}?>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="nome">Nome da Área</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="nome" required placeholder="Ex.: Salão de Festas" value="<?=$edit['nome']?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="metragem">Metragem (m²)</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="metragem" required value="<?=$edit['metragem']?>">
        </div>
        <div class="form-group col-md-4">
            <label for="taxa">Taxa de Reserva (opcional)</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="taxa" id="maskMoney" required value="<?=maskComponent::mask($edit['taxa'], 'taxa') ?>"> 
        </div>
        <div class="form-group col-md-4">
            <label for="lotacaoMax">Lotação Máxima</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="lotacaoMax" required value="<?=$edit['lotacaoMax']?>">
        </div>
    </div>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">
    <input type="hidden" name="id" value="<?=$edit['id']?>">

    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-info mr-2 buttonEnviar">Salvar Alterações</button>
            <a class="btn btn-sm btn-outline-secondary" data-dismiss="modal" role="button">Fechar</a>
        </div>
    </div>
</form>

views/areas-comuns/lista-area.php
<?
use app\components\alertComponent;
use app\components\maskComponent;
use app\components\modalComponent;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$this->title = 'Listagem | Áreas Comuns';

$url_site = Url::base(true);

if (isset($_GET['myAlert'])) {
    echo alertComponent::myAlert($_GET['myAlert']['type'], $_GET['myAlert']['msg']);
}
?>

<h3 class="text-center mt-5 mb-4">Áreas Comuns Cadastradas</h3>
<div class="table-responsive">
    <table id="listaArea" class="table table-striped my-4 table-hover shadow bg-white rounded">
    <tr>
        <th scope="col">Condomínio</td>
        <th scope="col">Área Comum</td>
        <th scope="col">Metragem</td>
        <th scope="col">Taxa de Reserva</td>
        <th scope="col">Lotação Máxima</td>
        <th scope="col">Data Cadastro</th>
        <th scope="col" colspan="2">Ações</th>
    </tr>
    <? foreach ($areas as $dadosArea) {?>
        <tr data-id="<?=$dadosArea['id']?>">
            <td><?=$dadosArea['nomeCondominio'] ?></td>
            <td><?=$dadosArea['nome'] ?></td>
            <td><?=$dadosArea['metragem'] ?></td>
            <td><?=maskComponent::mask($dadosArea['taxa'], 'taxa') ?></td>
            <td><?=$dadosArea['lotacaoMax'] ?></td>
            <td><?=yii::$app -> formatter -> format($dadosArea['dataCadastro'], 'date') ?></td>
            <td>
                <a class="text-dark h4 openModal" href="<?=$url_site?>/index.php?r=areas-comuns/edita-area&id=<?=$dadosArea['id']?>"><i class="bi bi-pencil-square"></i></a>
                <a class="text-dark h4" href="<?=$url_site?>/index.php?r=areas-comuns/deleta-area&id=<?=$dadosArea['id']?>"><i class="bi bi-trash3-fill"></i></a>
            <td>
        </tr>
    <? } ?>
    </table>
</div>
<div class="row mb-5">
    <div class="col-12 col-md-4">
        <a href="?r=areas-comuns/cadastro-area" class="text-left text-dark h6"><i class="bi bi-plus-circle-fill"></i> Adicionar Área Comum</a>
    </div>
    <div class="col-12 col-md-4 text-center d-flex justify-content-center">
        <?= LinkPager::widget([
            'pagination' => $paginacao,
            'linkContainerOptions' => ['class' => 'page-item'], 
            'linkOptions' => ['class' => 'page-link text-dark'],
            'disabledListItemSubTagOptions' => ['class' => 'page-link text-dark']
        ]) ?>
    </div>
    <div class="col-12 col-md-4">
        <p class="text-right ">Total de registros 
            <span class="badge badge-dark totalRegistros ">
                <?= $paginacao->totalCount ?>
            </span>
        </p>
    </div>
</div>

<?=modalComponent::initModal();?>