controllers/PetsController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\PetsModel;
use Yii;

class PetsController extends Controller{
    public function actionListaPets(){
        if(Yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }

        $query = (new \yii\db\Query())
        ->select(
            "pet.id,
            cond.nomeCondominio,
            bloco.nomeBloco,
            uni.nomeUnidade,
            pet.nome,
            pet.especie,
            pet.raca,
            pet.porte,
            pet.cor,
            pet.from_condominio,
            pet.from_bloco,
            pet.from_unidade")
        ->from('t_pets pet')
        ->innerJoin('t_condominio cond', 'cond.id = pet.from_condominio')
        ->innerJoin('t_bloco bloco', 'bloco.id = pet.from_bloco')
        ->innerJoin('t_unidade uni', 'uni.id = pet.from_unidade');


        $paginacao= new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $pets = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('lista-pets', [
            'pets' => $pets,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastroPets(){
        return $this->render('cadastro-pets');
    }

    public function actionRealizaCadastroPets(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new PetsModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['pets/lista-pets']);
        }
        return $this->render('cadastro-pets');
    }


    public function actionEditaPets(){
        $this->layout = false;
        $request = \yii::$app->request;
        if ($request->isGet) {
            $query = PetsModel::find();
            $pets = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-pets',[
            'edit' => $pets
        ]);
    }

    public function actionRealizaEdicao(){
        $request = \yii::$app->request;
        
        if ($request->isPost) {

            $model = PetsModel::findOne($request->post('id'));
            $model->attributes = $request->post();
        
            if ($model->update()) {
                return $this->redirect(['pets/lista-pets',
                    'myAlert' => [
                        'type' => 'success',
                        'msg' => 'Registro editado com sucesso!'
                    ]
                ]);
            } else {
                return $this->redirect(['pets/lista-pets',
                    'myAlert' => [
                        'type' => 'warning',
                        'msg' => 'Nenhum registro foi editado.'
                    ]
                ]);
            }
        }
    }

    public function actionDeletaPets(){
        $request = \yii::$app->request;

        if ($request->isGet) {
            $model = PetsModel::findOne($request->get('id'));
            if ($model->delete()) {
                return $this->redirect(['pets/lista-pets',
                    'myAlert' => [
                        'type' => 'success',
                        'msg' => 'Registro deletado com sucesso!'
                    ]
                ]);
            } else {
                return $this->redirect(['pets/lista-pets',
                'myAlert' => [
                    'type' => 'danger',
                    'msg' => 'Não foi possível deletar o registro.'
                    ]
                ]);
            }
        }
    }
}
?>

views/pets/cadastro-pets.php
<?
use yii\helpers\Url;
use app\controllers\CondominiosController;

$this->title = 'Cadastrar | Pets';

$url_site = Url::base(true);
?>

<h3 class="text-center mt-5" >Cadastrar Pets</h3>
<form id="cadastroPets" action="<?= Url::to(['pets/realiza-cadastro-pets'])?>" class="my-5" method="post">
    <div class="form-row">

        <div class="form-group col-md-4">
        <label for="nomeCondominio">Condomínio</label>
            <select class="form-control shadow mb-3 bg-white rounded fromCondominio" name="from_condominio" id="nomeCondominio" required>
                <option value="" disabled selected>Selecione o Condomínio</option>
                <? foreach(CondominiosController::listaCondominioSelect() as $dado){?>
                        <option value="<?=$dado['id']?>"><?=$dado['nomeCondominio']?></option>
                <?}?>
            </select>
        </div>

        <div class="form-group col-md-4">
        <label for="nomeBloco">Bloco</label>
            <select class="form-control shadow mb-3 bg-white rounded fromBloco" name="from_bloco" id="nomeBloco" required>
            
            </select>
        </div>

        <div class="form-group col-md-4">
        <label for="nomeUnidade">Unidade</label>
            <select class="form-control shadow mb-3 bg-white rounded fromUnidade" name="from_unidade" id="nomeUnidade" required>
            
            </select>
        </div>

    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="nome">Nome</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="nome" required>
        </div>

        <div class="form-group col-md-4">
            <label for="especie">Espécie</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="especie" placeholder="Ex.: Gato/Cachorro" required>
        </div>

        <div class="form-group col-md-4">
            <label for="raca">Raça</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="raca" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="porte">Porte</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="porte"  required>
                <option value="" disabled selected>Selecione o porte</option>
                <option value="P">Pequeno</option>
                <option value="M">Médio</option>
                <option value="G">Grande</option>
            </select>
        </div>

        <div class="form-group col-md-6">
            <label for="cor">Cor</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="cor">
        </div>
    </div> 

    <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">
    
    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-info mr-2 buttonEnviar">Cadastrar</button>
            <a class="btn btn-sm btn-outline-secondary" href="?r=pets/lista-pets" role="button">Ir para a listagem</a>
        </div>
    </div>
</form>

views/pets/edita-pets.php
<?
use yii\helpers\Url;
use app\controllers\CondominiosController;
use app\components\selectedComponent;
use app\controllers\BlocosController;
use app\controllers\UnidadesController;

$url_site = Url::base(true);
?>

<h3 class="text-center mt-3" >Editar Pets</h3>
<form id="cadastroPets" action="<?= Url::to(['pets/realiza-edicao'])?>" class="my-5" method="post">
    <div class="form-row">

        <div class="form-group col-md-6">
        <label for="nomeCondominio">Condomínio</label>
            <select class="form-control shadow mb-3 bg-white rounded fromCondominio" name="from_condominio" id="nomeCondominio" required>
                <option value="" disabled selected>Selecione o Condomínio</option>
                <? foreach(CondominiosController::listaCondominioSelect() as $dado){?>
                        <option value="<?=$dado['id']?>"<?=selectedComponent::isSelected($dado['id'], $edit['from_condominio'])?>><?=$dado['nomeCondominio']?></option>
                <?}?>
            </select>
        </div>

        <div class="form-group col-md-3">
        <label for="nomeBloco">Bloco</label>
            <select class="form-control shadow mb-3 bg-white rounded fromBloco" name="from_bloco" id="nomeBloco" required>
                <option value="" disabled selected>Selecione o Bloco</option>
                <? foreach(BlocosController::listaBlocoSelectFrom($edit['from_condominio']) as $dado){?>
                        <option value="<?=$dado['id']?>"<?=selectedComponent::isSelected($dado['id'], $edit['from_bloco'])?>><?=$dado['nomeBloco']?></option>
                <?}?>
            </select>
        </div>

        <div class="form-group col-md-3">
        <label for="nomeUnidade">Unidade</label>
            <select class="form-control shadow mb-3 bg-white rounded fromUnidade" name="from_unidade" id="nomeUnidade" required>
            <option value="" disabled selected>Selecione a Unidade</option>
                <? foreach(UnidadesController::listaUnidadeSelectFrom($edit['from_bloco']) as $dado){?>
                        <option value="<?=$dado['id']?>"<?=selectedComponent::isSelected($dado['id'], $edit['from_unidade'])?>><?=$dado['nomeUnidade']?></option>
                <?}?>
            </select>
        </div>

    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="nome">Nome</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="nome" value="<?=$edit['nome']?>" required>
        </div>

        <div class="form-group col-md-4">
            <label for="especie">Espécie</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="especie" placeholder="Ex.: Gato/Cachorro" value="<?=$edit['especie']?>" required>
        </div>

        <div class="form-group col-md-4">
            <label for="raca">Raça</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="raca" value="<?=$edit['raca']?>" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="porte">Porte</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="porte"  required>
                <option value="" disabled selected>Selecione o porte</option>
                <option value="P" <?=('P' == $edit['porte'] ? 'selected' : '')?>>Pequeno</option>
                <option value="M" <?=('M' == $edit['porte'] ? 'selected' : '')?>>Médio</option>
                <option value="G" <?=('G' == $edit['porte'] ? 'selected' : '')?>>Grande</option>
            </select>
        </div>

        <div class="form-group col-md-6">
            <label for="cor">Cor</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="cor" value="<?=$edit['cor']?>">
        </div>
    </div> 

    <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">
    <input type="hidden" name="id" value="<?=$edit['id']?>">

    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-info mr-2 buttonEnviar">Salvar Alterações</button>
            <a class="btn btn-sm btn-outline-secondary" data-dismiss="modal" role="button">Fechar</a>
        </div>
    </div>
</form>

views/pets/lista-pets.php
<?
use app\components\alertComponent;
use app\components\maskComponent;
use app\components\modalComponent;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$this->title = 'Listagem | Pets';

$url_site = Url::base(true);

if (isset($_GET['myAlert'])) {
    echo alertComponent::myAlert($_GET['myAlert']['type'], $_GET['myAlert']['msg']);
}
?>

<h3 class="text-center mt-5 mb-4">Pets Cadastrados</h3>
<div class="table-responsive">
    <table id="listaPets" class="table table-striped my-3 table-hover shadow bg-white rounded">
        <tr>
            <th scope="col">Condomínio</th>
            <th scope="col">Bloco</th>
            <th scope="col">Unidade</th> 
            <th scope="col">Nome</th>
            <th scope="col">Espécie</th>
            <th scope="col">Raça</th>
            <th scope="col">Porte</th>
            <th scope="col">Cor</th>
            <th scope="col" colspan="2">Ações</th>
        </tr>
        <? foreach ($pets as $dados) { ?> 
            <tr data-id="<?= $dados['id'] ?>">
                <td><?= $dados['nomeCondominio'] ?></td>
                <td><?= $dados['nomeBloco'] ?></td>
                <td><?= $dados['nomeUnidade'] ?></td> 
                <td><?= $dados['nome'] ?></td>
                <td><?= $dados['especie'] ?></td>
                <td><?= $dados['raca'] ?></td>
                <td><?= $dados['porte'] ?></td>
                <td><?= $dados['cor'] ?></td>
                <td>
                    <a class="text-dark h4 openModal" href="<?=$url_site?>/index.php?r=pets/edita-pets&id=<?=$dados['id']?>"><i class="bi bi-pencil-square"></i></a>
                    <a class="text-dark h4" href="<?=$url_site?>/index.php?r=pets/deleta-pets&id=<?=$dados['id']?>"><i class="bi bi-trash3-fill"></i></a>
                <td>
            </tr>
        <? } ?>
    </table>
</div>
<div class="row mb-5">
    <div class="col-12 col-md-4">
        <a href="?r=pets/cadastro-pets" class="text-left text-dark h6"><i class="bi bi-plus-circle-fill"></i> Adicionar Pets</a>
    </div>
    <div class="col-12 col-md-4 text-center d-flex justify-content-center">
        <?= LinkPager::widget([
            'pagination' => $paginacao,
            'linkContainerOptions' => ['class' => 'page-item'], 
            'linkOptions' => ['class' => 'page-link text-dark'],
            'disabledListItemSubTagOptions' => ['class' => 'page-link text-dark']
        ]) ?>
    </div>
    <div class="col-12 col-md-4">
        <p class="text-right ">Total de registros
            <span class="badge badge-dark totalRegistros ">
                <?= $paginacao->totalCount ?>
            </span>
        </p>
    </div>
</div>

<?=modalComponent::initModal();?>