controllers/CondominiosController.php
<?
namespace app\controllers;

use app\components\maskComponent;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\CondominiosModel;
use Yii;

class CondominiosController extends Controller{
    public function actionListaCondominio(){
        if(Yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        $query = (new \yii\db\Query())
        ->select([
        "cond.id",
        "adm.nome",
        "cond.nomeCondominio",
        "cond.qtdBlocos",
        "cond.lougradouro",
        "cond.numero",
        "cond.bairro",
        "cond.cidade",
        "cond.estado",
        "cond.cep",
        "cond.sindico",
        "cond.dataCadastro",
        "cond.from_administradora"])
        ->from('t_condominio cond')
        ->innerJoin('t_administradora adm', 'adm.id = cond.from_administradora');

        $paginacao= new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $condominios = $query->orderBy('nomeCondominio')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('lista-condominio', [
            'condominios' => $condominios,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastroCondominio(){
        return $this->render('cadastro-condominio');
    }

    public function actionRealizaCadastroCondominio(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new CondominiosModel();
            foreach($request->post() as $field=>$value){
                if($field == 'cep'){
                    $getMani[$field] = maskComponent::desMask($value);
                }else{
                    $getMani[$field] = $value;
                }
            }
            $model->attributes = $getMani;
            $model->save();
            return $this->redirect(['condominios/lista-condominio']);
        }
        return $this->render('cadastro-condominio');
    }

    public static function listaCondominioSelect(){
        $query = CondominiosModel::find();

        return $query->orderBy('nomeCondominio')->all();
    }

    public function actionEditaCondominio(){
        $this->layout = false;
        $request = \yii::$app->request;
        if ($request->isGet) {
            $query = CondominiosModel::find();
            $condominios = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-condominio',[
            'edit' => $condominios
        ]);
    }

    public function actionRealizaEdicao(){
        $request = \yii::$app->request;
        
        if ($request->isPost) {

            $model = CondominiosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
        
            if ($model->update()) {
                return $this->redirect(['condominios/lista-condominio',
                    'myAlert' => [
                        'type' => 'success',
                        'msg' => 'Registro editado com sucesso!'
                    ]
                ]);
            } else {
                return $this->redirect(['condominios/lista-condominio',
                    'myAlert' => [
                        'type' => 'warning',
                        'msg' => 'Nenhum registro foi editado.'
                    ]
                ]);
            }
        }
    }

    public function actionDeletaCondominio(){
        $request = \yii::$app->request;

        if ($request->isGet) {
            $model = CondominiosModel::findOne($request->get('id'));
            if ($model->delete()) {
                return $this->redirect(['condominios/lista-condominio',
                    'myAlert' => [
                        'type' => 'success',
                        'msg' => 'Registro deletado com sucesso!'
                    ]
                ]);
            } else {
                return $this->redirect(['condominios/lista-condominio',
                'myAlert' => [
                    'type' => 'danger',
                    'msg' => 'Não foi possível deletar o registro.'
                    ]
                ]);
            }
        }
    }
}
?>

views/condominios/cadastro-condominio.php
<?
use yii\helpers\Url;
use app\controllers\AdministradorasController;
use app\components\estadosComponent;

$this->title = 'Cadastrar | Condomínio';

$url_site = Url::base($schema = true);

?>

<h3 class="text-center mt-5" >Cadastrar Condomínios</h3>
<form id="cadastroCondominio" action="<?= Url::to(['condominios/realiza-cadastro-condominio'])?>" method="post">
    <div class="form-row mt-4">
        <div class="form-group col-md-12">
            <label for="from_administradora">Administradora</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="from_administradora" required>
                <option value="" >Selecione a Administradora</option>
                <? foreach(AdministradorasController::listaAdministradoraSelect() as $dado){?>
                        <option value="<?=$dado['id']?>"><?=$dado['nome']?></option>
                <?}?>
            </select>
        </div>
    </div>

    <div class="form-row mt-4">
        <div class="form-group col-md-9">
            <label for="nomeCondominio">Nome do condomínio</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="nomeCondominio" id="nomeCondominio"  required>
        </div>
        <div class="form-group col-md-3">
            <label for="qtdBlocos">Quantidade de Blocos</label>
            <input type="number" min="1" class="form-control shadow mb-3 bg-white rounded" name="qtdBlocos" id="qtdBlocos"  required>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <h5>Endereço</h5>
        </div>
        <div class="form-group col-md-3">
            <label for="cep">CEP</label>
            <input type="text" maxlength="8" class="form-control shadow mb-3 bg-white rounded" name="cep" id="cep">
        </div>
        <div class="form-group col-md-3">
            <label for="estado">Estado</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="estado" id="estado">
                <option value="" disabled selected>Selecione</option>
                <?
                foreach(estadosComponent::estados() as $sig=>$uf) {
                   echo '<option id="uf" value="'.$sig.'"'.'>'.$uf.' </option>';}
                ?>
            </select>
        </div> 
        <div class="form-group col-md-6">
           <label for="cidade">Cidade</label>
           <input type="text" class="form-control shadow mb-3 bg-white rounded" name="cidade" id="cidade">
       </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="bairro">Bairro</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="bairro">
        </div>
        <div class="form-group col-md-6">
            <label for="lougradouro">Lougradouro</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="lougradouro" id="lougradouro" >
        </div>
        <div class="form-group col-md-2">
            <label for="numero">Número</label>
            <input type="number" min="1" class="form-control shadow mb-3 bg-white rounded" name="numero" >
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <h5>Síndico</h5>
        </div>
        <div class="form-group col-md-12">
            <label for="sindico">Nome completo do síndico(a)</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="sindico" id="sindico" required>
        </div>
    </div>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">
    
    <div class="row mb-5">
        <div class="col-12 mb-4">
            <button type="submit" class="btn btn-info mr-2 buttonEnviar">Cadastrar</button>
            <a class="btn btn-sm btn-outline-secondary" href="?r=condominios/lista-condominio" role="button">Ir para a listagem</a>
        </div>
    </div>
</form>

views/condominios/edita-condominio.php
<?
use yii\helpers\Url;
use app\controllers\AdministradorasController;
use app\components\estadosComponent;
use app\components\maskComponent;
use app\components\selectedComponent;

$url_site = Url::base(true);
?>

<h3 class="text-center mt-3" >Editar Condomínio</h3>
<form id="cadastroCondominio" action="<?= Url::to(['condominios/realiza-edicao'])?>" method="post">
    <div class="form-row mt-4">
        <div class="form-group col-md-12">
            <label for="from_administradora">Administradora</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="from_administradora" required>
                <option value="" >Selecione a Administradora</option>
                <? foreach(AdministradorasController::listaAdministradoraSelect() as $dado){?>
                        <option value="<?=$dado['id']?>"<?=selectedComponent::isSelected($dado['id'], $edit['from_administradora'])?>><?=$dado['nome']?></option>
                <?}?>
            </select>
        </div>
    </div>

    <div class="form-row mt-4">
        <div class="form-group col-md-9">
            <label for="nomeCondominio">Nome do condomínio</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="nomeCondominio" id="nomeCondominio" value="<?=$edit['nomeCondominio']?>" required>
        </div>
        <div class="form-group col-md-3">
            <label for="qtdBlocos">Quantidade de Blocos</label>
            <input type="number" min="1" class="form-control shadow mb-3 bg-white rounded" name="qtdBlocos" id="qtdBlocos" value="<?=$edit['qtdBlocos']?>" required>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <h5>Endereço</h5>
        </div>
        <div class="form-group col-md-3">
            <label for="cep">CEP</label>
            <input type="text" maxlength="8" class="form-control shadow mb-3 bg-white rounded" name="cep" id="cep" value="<?=maskComponent::mask($edit['cep'], 'cep')?>">
        </div>
        <div class="form-group col-md-3">
            <label for="estado">Estado</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="estado" id="estado">
                <option value="" disabled selected>Selecione</option>
                <?
                foreach(estadosComponent::estados() as $sig=>$uf) { ?>
                  <option value="<?=$sig?>" <?=($edit['estado'] == $sig ? 'selected' : '' )?>><?=$uf?></option>
                <?}?>
            </select>
        </div> 
        <div class="form-group col-md-6">
           <label for="cidade">Cidade</label>
           <input type="text" class="form-control shadow mb-3 bg-white rounded" name="cidade" id="cidade" value="<?=$edit['cidade']?>">
       </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="bairro">Bairro</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="bairro" value="<?=$edit['bairro']?>">
        </div>
        <div class="form-group col-md-6">
            <label for="lougradouro">Lougradouro</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="lougradouro" id="lougradouro" value="<?=$edit['lougradouro']?>">
        </div>
        <div class="form-group col-md-2">
            <label for="numero">Número</label>
            <input type="number" min="1" class="form-control shadow mb-3 bg-white rounded" name="numero" value="<?=$edit['numero']?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <h5>Síndico</h5>
        </div>
        <div class="form-group col-md-12">
            <label for="sindico">Nome completo do síndico(a)</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="sindico" id="sindico" value="<?=$edit['sindico']?>" required>
        </div>
    </div>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">
    <input type="hidden" name="id" value="<?=$edit['id']?>">

    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-info mr-2 buttonEnviar">Salvar Alterações</button>
            <a class="btn btn-sm btn-ouline-secondary" data-dismiss="modal" role="button">Fechar</a>
        </div>
    </div>
</form>

views/condominios/lista-condominio.php
<?
use app\components\alertComponent;
use app\components\maskComponent;
use app\components\modalComponent;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$this->title = 'Listagem | Condomínios';

$url_site = Url::base(true);

if (isset($_GET['myAlert'])) {
    echo alertComponent::myAlert($_GET['myAlert']['type'], $_GET['myAlert']['msg']);
}
?>

<h3 class="text-center mt-5 mb-4">Condomínios Cadastrados</h3>
<div class="table-responsive">
    <table id="listaCondominio" class="table table-striped my-4 table-hover shadow bg-white rounded">
    <tr>
        <th scope="col">Administradora</td>
        <th scope="col">Condomínio</td>
        <th scope="col">Blocos</td> 
        <th scope="col">Endereço</td>
        <th scope="col">Síndico</td>
        <th scope="col">Data Cadastro</th>
        <th scope="col" colspan="2">Ações</th>
    </tr>
    <? foreach ($condominios as $dadosCondo) {?>
         <tr data-id="<?=$dadosCondo['id']?>">
            <td><?=$dadosCondo['nome'] ?></td> 
            <td><?=$dadosCondo['nomeCondominio'] ?></td>
            <td><?=$dadosCondo['qtdBlocos'] ?></td>
            <td><?=$dadosCondo['lougradouro'].', '.$dadosCondo['numero'].' | '.$dadosCondo['bairro'].' | '.$dadosCondo['cidade'].' - '.$dadosCondo['estado'].' | '.maskComponent::mask($dadosCondo['cep'], 'cep')?></td>
            <td><?=$dadosCondo['sindico'] ?></td>
            <td><?=yii::$app -> formatter -> format($dadosCondo['dataCadastro'], 'date') ?></td>
            <td>
                <a class="text-dark h4 openModal" href="<?=$url_site?>/index.php?r=condominios/edita-condominio&id=<?=$dadosCondo['id']?>"><i class="bi bi-pencil-square"></i></a>
                <a class="text-dark h4" href="<?=$url_site?>/index.php?r=condominios/deleta-condominio&id=<?=$dadosCondo['id']?>"><i class="bi bi-trash3-fill"></i></a>
            <td>
        </tr>
    <? } ?>
    </table>
</div>
<div class="row mb-5">
    <div class="col-12 col-md-4">
        <a href="?r=condominios/cadastro-condominio" class="text-left text-dark h6"><i class="bi bi-plus-circle-fill"></i> Adicionar Condomínio</a>
    </div>
    <div class="col-12 col-md-4 text-center d-flex justify-content-center">
        <?= LinkPager::widget([
            'pagination' => $paginacao,
            'linkContainerOptions' => ['class' => 'page-item'], 
            'linkOptions' => ['class' => 'page-link text-dark'],
            'disabledListItemSubTagOptions' => ['class' => 'page-link text-dark']
        ]) ?>
    </div>
    <div class="col-12 col-md-4">
        <p class="text-right ">Total de registros 
            <span class="badge badge-dark totalRegistros ">
                <?= $paginacao->totalCount ?>
            </span>
        </p>
    </div>
</div>

<?=modalComponent::initModal();?>