controllers/BlocosController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocosModel;
use Yii;

class BlocosController extends Controller{
    public function actionListaBloco(){
        if(Yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        $query = (new \yii\db\Query())
        ->select(
            "bloco.id,
            cond.nomeCondominio,
            bloco.nomeBloco,
            bloco.andares,
            bloco.qtdUnidades,
            bloco.dataCadastro,
            bloco.from_condominio")
        ->from('t_bloco bloco')
        ->innerJoin('t_condominio cond', 'cond.id = bloco.from_condominio');

        $paginacao= new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $blocos = $query->orderBy('nomeBloco')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('lista-bloco', [
            'blocos' => $blocos,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastroBloco(){
        return $this->render('cadastro-bloco');
    }

    public function actionRealizaCadastroBloco(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/lista-bloco']);
        }
        return $this->render('cadastro-bloco');
    }

    public static function listaBlocoSelect(){
        $query = BlocosModel::find();

        return $query->orderBy('nomeBloco')->all();
    }

    public static function listaBlocoSelectFrom($from){
        $query = BlocosModel::find();
        $data = $query->where(['from_condominio' => $from])->orderBy('nomeBloco')->all();
        return $data;
    }
    
    public function actionListaBlocoApi(){
        $request = \yii::$app->request;
        $query = BlocosModel::find();
        $data = $query->where(['from_condominio' => $request->post()])->orderBy('nomeBloco')->all();

        $dados = array();
        $i = 0;

        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nomeBloco'] = $d['nomeBloco'];
            $i++;
        }
        return json_encode($dados);
    }

    public function actionEditaBloco(){
        $this->layout = false;
        $request = \yii::$app->request;
        if ($request->isGet) {
            $query = BlocosModel::find();
            $blocos = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-bloco',[
            'edit' => $blocos
        ]);
    }

    public function actionRealizaEdicao(){
        $request = \yii::$app->request;
        
        if ($request->isPost) {

            $model = BlocosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
        
            if ($model->update()) {
                return $this->redirect(['blocos/lista-bloco',
                'myAlert' => [
                    'type' => 'success',
                    'msg' => 'Registro editado com sucesso!'
                ]
            ]);
            } else {
                return $this->redirect(['blocos/lista-bloco',
                'myAlert' => [
                    'type' => 'warning',
                    'msg' => 'Nenhum registro foi editado.'
                ]
            ]);
            }
        }
    }

    public function actionDeletaBloco(){
        $request = \yii::$app->request;

        if ($request->isGet) {
            $model = BlocosModel::findOne($request->get('id'));
            if ($model->delete()) {
                return $this->redirect(['blocos/lista-bloco',
                    'myAlert' => [
                        'type' => 'success',
                        'msg' => 'Registro deletado com sucesso!'
                    ]
                ]);
            } else {
                return $this->redirect(['blocos/lista-bloco',
                'myAlert' => [
                    'type' => 'danger',
                    'msg' => 'Não foi possível deletar o registro.'
                    ]
                ]);
            }
        }
    }
}
?>

views/blocos/cadastro-bloco.php
<?
use yii\helpers\Url;
use app\controllers\CondominiosController;

$this->title = 'Cadastrar | Bloco';

$url_site = Url::base($schema = true);
?>

<h3 class="text-center mt-5" >Cadastrar Blocos</h3>
<form id="cadastroBloco" action="<?= Url::to(['blocos/realiza-cadastro-bloco'])?>" class="my-5" method="post">
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="condominioBloco">A qual condomínio este bloco pertence?</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="from_condominio"  required>
                <option value="" disabled selected>Selecione o Condomínio</option>
                <? foreach(CondominiosController::listaCondominioSelect() as $dado){?>
                        <option value="<?=$dado['id']?>"><?=$dado['nomeCondominio']?></option>
                <?}?>
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="nomeBloco">Nomenclatura do Bloco</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="nomeBloco" id="nomeBloco" placeholder="Ex.: Bloco A / Bloco 01..."required>
        </div>
        <div class="form-group col-md-4">
            <label for="andares">Quantidade de Andares</label>
            <input type="number" min="1" class="form-control shadow mb-3 bg-white rounded" name="andares" id="andares" required>
        </div>
        <div class="form-group col-md-4">
            <label for="qtdUnidades">Quantidade de Unidades por andar</label>
            <input type="number" min="1" class="form-control shadow mb-3 bg-white rounded" name="qtdUnidades" id="qtdUnidades" required>
        </div>
    </div>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">
    
    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-info mr-2 buttonEnviar">Cadastrar</button>
            <a class="btn btn-sm btn-outline-secondary" href="?r=blocos/lista-bloco" role="button">Ir para a listagem</a>
        </div>
    </div>
</form>

views/blocos/edita-bloco.php
<?
use app\components\selectedComponent;
use yii\helpers\Url;
use app\controllers\CondominiosController;

$url_site = Url::base(true);
?>

<h3 class="text-center mt-3" >Editar Bloco</h3>
<form id="cadastroBloco" action="<?= Url::to(['blocos/realiza-edicao'])?>" class="my-5" method="post">
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="condominioBloco">A qual condomínio este bloco pertence?</label>
            <select class="form-control shadow mb-3 bg-white rounded" name="from_condominio"  required>
                <option value="" disabled selected>Selecione o Condomínio</option>
                <? foreach(CondominiosController::listaCondominioSelect() as $dado){?>
                        <option value="<?=$dado['id']?>"<?=selectedComponent::isSelected($dado['id'], $edit['from_condominio'])?>><?=$dado['nomeCondominio']?></option>
                <?}?>
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="nomeBloco">Nomenclatura do Bloco</label>
            <input type="text" class="form-control shadow mb-3 bg-white rounded" name="nomeBloco" id="nomeBloco" placeholder="Ex.: Bloco A / Bloco 01..." value="<?=$edit['nomeBloco']?>" required>
        </div>
        <div class="form-group col-md-4">
            <label for="andares">Quantidade de Andares</label>
            <input type="number" min="1" class="form-control shadow mb-3 bg-white rounded" name="andares" id="andares" value="<?=$edit['andares']?>" required>
        </div>
        <div class="form-group col-md-4">
            <label for="qtdUnidades">Unidades por andar</label>
            <input type="number" min="1" class="form-control shadow mb-3 bg-white rounded" name="qtdUnidades" id="qtdUnidades" value="<?=$edit['qtdUnidades']?>" required>
        </div>
    </div>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">
    <input type="hidden" name="id" value="<?=$edit['id']?>">

    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-info mr-2 buttonEnviar">Salvar Alterações</button>
            <a class="btn btn-sm btn-outline-secondary" data-dismiss="modal" role="button">Fechar</a>
        </div>
    </div>
</form>

views/blocos/lista-bloco.php
<?
use app\components\alertComponent;
use app\components\modalComponent;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$this->title = 'Listagem | Blocos';

$url_site = Url::base(true);

if (isset($_GET['myAlert'])) {
    echo alertComponent::myAlert($_GET['myAlert']['type'], $_GET['myAlert']['msg']);
}
?>

<h3 class="text-center mt-5 mb-4">Blocos Cadastrados</h3>
<div class="table-responsive">
    <table id="listaBloco" class="table table-striped my-4 table-hover shadow bg-white rounded">
    <tr>
        <th scope="col">Condomínio</td>
        <th scope="col">Nomenclatura</td>
        <th scope="col">Qtd. Andares</td>
        <th scope="col">Unidades por Andar</td>
        <th scope="col">Data Cadastro</th>
        <th scope="col" colspan="2">Ações</th>
    </tr>
    <? foreach ($blocos as $dadosBloco) {?>
        <tr data-id="<?=$dadosBloco['id']?>">
            <td><?=$dadosBloco['nomeCondominio'] ?></td>
            <td><?=$dadosBloco['nomeBloco'] ?></td>
            <td><?=$dadosBloco['andares'] ?></td>
            <td><?=$dadosBloco['qtdUnidades'] ?></td>
            <td><?=yii::$app -> formatter -> format($dadosBloco['dataCadastro'], 'date') ?></td>
            <td>
                <a class="text-dark h4 openModal" href="<?=$url_site?>/index.php?r=blocos/edita-bloco&id=<?=$dadosBloco['id']?>"><i class="bi bi-pencil-square"></i></a>
                <a class="text-dark h4" href="<?=$url_site?>/index.php?r=blocos/deleta-bloco&id=<?=$dadosBloco['id']?>"><i class="bi bi-trash3-fill"></i></a>
            <td>
        </tr>
    <? } ?>
    </table>
</div>
<div class="row mb-5">
    <div class="col-12 col-md-4">
        <a href="?r=blocos/cadastro-bloco" class="text-left text-dark h6"><i class="bi bi-plus-circle-fill"></i> Adicionar Bloco</a>
    </div>
    <div class="col-12 col-md-4 text-center d-flex justify-content-center">
        <?= LinkPager::widget([
            'pagination' => $paginacao,
            'linkContainerOptions' => ['class' => 'page-item'], 
            'linkOptions' => ['class' => 'page-link text-dark'],
            'disabledListItemSubTagOptions' => ['class' => 'page-link text-dark']
        ]) ?>
    </div>
    <div class="col-12 col-md-4">
        <p class="text-right ">Total de registros 
            <span class="badge badge-dark totalRegistros ">
                <?= $paginacao->totalCount ?>
            </span>
        </p>
    </div>
</div>

<?=modalComponent::initModal();?>